src/model.rs
```console
$ echo '{"Caller":"ServeHTTP [lib/common/common.go:1369]","Level":"info","Message":"success","Time":"2020-12-31T08:22:27.472085502Z"}' | hl -P
---         |(?)| caller='ServeHTTP [lib/common/common.go:1369]' level='info' message='success' time='2020-12-31T08:22:27.472085502Z'
```
```console
$ echo '{"Caller":"ServeHTTP [lib/common/common.go:1369]","Level":"info","Message":"success","Time":"2020-12-31T08:22:27.472085502Z"}' | ./target/debug/hl -P
Dec 31 08:22:27.472 |INF| success @ ServeHTTP [lib/common/common.go:1369]
```
=> new: support capitalized key

Cargo.lock, Cargo.toml, src/model.rs
=> fix: add support for lowercase message field

.github/workflows/publish.yml, Cargo.lock, Cargo.toml
new: added some more targets
* amd64-linux-gnu
* arm64-linux-musl
* arm64-linux-gnu
=> new: added some more targets

Cargo.lock, Cargo.toml, README.md, benches/json.rs, benches/parse-and-format.rs, benches/theme.rs, src/app.rs, src/console.rs, src/datefmt.rs, src/error.rs, src/filtering.rs, src/fmtx.rs, src/formatting.rs, src/index.rs, src/input.rs, src/level.rs, src/main.rs, src/model.rs, src/scanning.rs, src/theme.rs, src/themecfg.rs, src/timeparse.rs, src/timezone.rs, src/types.rs
=> new: Added follow mode with message sorting by timestamp

Cargo.lock, Cargo.toml, src/model.rs
=> fix: fixed filtering by fields in case number of fields is greater than 32

Cargo.lock, Cargo.toml, src/formatting.rs, src/model.rs
=> new: Added support for numeric `caller-line` predefined field

Cargo.lock, Cargo.toml, src/app.rs, src/formatting.rs, src/index.rs, src/model.rs
=> new: Added support for an arbitrary prefix before JSON message

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/app.rs
This regression has been introduced in v0.23.2
=> fix: Fixed missing new-line characters in follow mode

Cargo.lock, Cargo.toml, src/app.rs, src/error.rs, src/formatting.rs, src/index.rs, src/lib.rs, src/logfmt/de.rs, src/logfmt/error.rs, src/logfmt/mod.rs, src/logfmt/raw.rs, src/model.rs
The `--allow-prefix` option is currently incompatible with the `logfmt` format and is ignored.
=> new: Added support for logfmt format

Cargo.lock, Cargo.toml, src/model.rs
=> new: Added support for integer log levels

Cargo.lock, Cargo.toml, src/model.rs
=> new: Remove trailing whitespace in message and string values

Cargo.lock, Cargo.toml, etc/defaults/config-ecs.yaml, etc/defaults/config-k8s.yaml, src/model.rs, src/settings.rs
=> new: Added support for levels determined by field presence

Cargo.lock, Cargo.toml, README.md
=> new: Added an example how to use `!~=` operator in field filter

Cargo.lock, Cargo.toml, src/scanning.rs
Fixes regression introduced in #138
=> fix: Fixed parsing of the last line without trailing new-line characters

Cargo.lock, Cargo.toml, etc/defaults/themes/neutral.yaml, etc/defaults/themes/universal-blue.yaml, etc/defaults/themes/universal.yaml
Changed object and array separators style in `universal` and `neutral` themes
=> new: Changed object and array separators style in universal and neutral themes

Cargo.lock, Cargo.toml, etc/defaults/themes/classic-plus.yaml, etc/defaults/themes/dmt.yaml, etc/defaults/themes/lsd.yaml, etc/defaults/themes/one-dark-blue-truecolor.yaml, etc/defaults/themes/one-dark-blue-x.yaml, etc/defaults/themes/one-dark-blue.yaml, etc/defaults/themes/one-dark-green-truecolor.yaml, etc/defaults/themes/one-dark-green-x.yaml, etc/defaults/themes/one-dark-green.yaml
Several minor improvements in old themes for better compatibility with various terminals
=> new: Several minor improvements in old themes

Cargo.lock
reverting commit 64f52bbbaf9a427fd1307acf53aadab5b779a83a
=> build(deps): downgrade once_cell from 1.20.0 to 1.19.0

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs
* fix: fixed wildcard handling on windows
=> merge release/0.29 into master

Cargo.lock, Cargo.toml, crate/serde-logfmt/src/logfmt/de.rs
=> fix(logfmt): fixed parsing of empty unquoted values

Cargo.lock, Cargo.toml, crate/serde-logfmt/Cargo.toml, crate/serde-logfmt/src/logfmt/de.rs, src/model.rs, src/settings.rs
=> merge release/0.30.3 into master

Cargo.lock, Cargo.toml, src/datefmt.rs, src/timestamp.rs, src/timezone.rs
=> perf: fixed reformatting optimization of utc timestamps (#725)

Cargo.lock, Cargo.toml, src/scanning.rs
=> fix: fixed hang on sub-string delimiter search (#744)

Cargo.lock, Cargo.toml, build/ci/coverage.sh, src/app.rs, src/config.rs, src/level.rs, src/main.rs, src/model.rs, src/settings.rs, src/theme.rs, src/themecfg.rs
=> fix: fixed errors on unknown level in configuration files

Cargo.lock, Cargo.toml, src/cli.rs
=> feat: changed help style

README.md
=> Update Arch Linux installation instruction

schema/json/config.schema.json
Adds configuration option for #901
=> feat(schema): added punctuation.caller-name-file-separator option

README.md, contrib/bin/screenshot.sh
This updates screenshots for #907.
=> feat: updated screenshots for #907

.github/workflows/release.yml
This pull request switches to using application token to push changes to the main branch.
=> build(release): added release workflow
