pamburus/hl

src/formatting.rs

```console
$ echo '{"emptyArray":[],"emptyObject":{}}' | hl -P
---         |(?)| emptyarray=[] emptyobject={ }
```
```console
$ echo '{"emptyArray":[],"emptyObject":{}}' | ./target/debug/hl -P
---         |(?)| emptyarray=[] emptyobject={}
```

fix: remove unneccessary space in empty object

---

src/app.rs
src/formatting.rs
src/main.rs

```console
$ echo '{"emptyString":"","zero":0,"emptyArray":[],"emptyObject":{},"false":false}' | hl -P
---         |(?)| emptystring='' zero=0 emptyarray=[] emptyobject={ } false=false
```
```console
$ echo '{"emptyString":"","zero":0,"emptyArray":[],"emptyObject":{},"false":false}' | ./target/debug/hl -P --hide-empty-fields
---         |(?)| zero=0 false=false
```

new: ignore empty fields

---

Cargo.lock
Cargo.toml
benches/re_match.rs
benches/ts_format.rs
benches/ts_parse.rs
benches/wild_match.rs
etc/defaults/config.yaml
src/main.rs
src/model.rs
src/settings.rs

* new: Added `ignore` and `hide` options into `fields` section, settings for predefined fields moved to `fields.predefined` section.
```yaml
fields:
predefined:
time:
names: [ts, TS, time, TIME, Time, _SOURCE_REALTIME_TIMESTAMP, __REALTIME_TIMESTAMP]
logger:
names: [logger, LOGGER, Logger]
level:
variants:
- names: [level, LEVEL, Level]
values:
debug: [debug]
info: [info, information]
warning: [warning, warn]
error: [error, err, fatal, critical, panic]
- names: [PRIORITY]
values:
debug: [7]
info: [6]
warning: [5, 4]
error: [3, 2, 1]
message:
names: [msg, message, MESSAGE, Message]
caller:
names: [caller, CALLER, Caller]
ignore: ['_*']
hide: []
```

new: configuration options to ignore and hide fields

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/error.rs
src/main.rs
src/types.rs

* new: Changed rust edition to 2021
* new: Upgraded dependencies
* `atoi` → v1
* `itoa` → v1
* `enum-map` → v2
* `clap` → v3

release 0.11.2

---

Cargo.lock
Cargo.toml
README.md
src/filtering.rs
src/main.rs

* new: Replaced `--hide`, `--show` and `--unhide` options with a single option `--hide` with advanced query:
* `header.content-type` to hide field `content-type` inside an object field `header`
* `*` to hide all
* `!*` to unhide all
* `!header.content-type` to unhide field `content-type` inside an object field `header`

release 0.12.0

---

.rustfmt.toml
Cargo.lock
Cargo.toml
etc/defaults/config.yaml
etc/defaults/themes/one-dark-green.yaml
src/app.rs
src/formatting.rs
src/main.rs
src/settings.rs

Example
```yaml
formatting:
punctuation:
logger-name-separator: ' ‣'
field-key-value-separator: ':'
string-opening-quote: "‘"
string-closing-quote: "’"
source-location-separator: '→ '
hidden-fields-indicator: ' ...'
level-left-separator: '│'
level-right-separator: '│'
```

new: configurable formatting added

---

Cargo.lock
Cargo.toml
benches/ts-format.rs
src/main.rs
src/types.rs

* new: Upgraded clap to v4 and updated most of the other packages
* new: Renamed flag `-h` to `-H` to allow `-h` to be used for help

new: Renamed flag `-h` to `-H`

---

Cargo.lock
Cargo.toml

Reason: https://github.com/time-rs/time/issues/293

new: Updated `time` crate to v0.2.27

---

Cargo.lock
Cargo.toml
src/index.rs
src/level.rs
src/lib.rs
src/main.rs
src/model.rs
src/settings.rs
src/theme.rs
src/themecfg.rs
src/types.rs

* new: Custom relaxed level parsing when specified on command line
It now accepts `e`, `w`, `i`, `d` shortcuts as in older versions as well as `err`, `wrn`, `warn`, `inf` and `dbg`
* changed: Renamed `-H | --hide` option back to `-h`, no more shortcut for `--help` flag

new: Command line options `-h` and `-l` are now compatible with older versions

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml

Theme `universal` is now set as default because it has greater compatibility with different terminals, in particular it works good both on dark and light terminals.
If you would like to keep `one-dark-green` theme default you can 
* Set environment variable `HL_THEME=one-dark-green`
* Or create/edit configuration file at `~/.config/hl/config.yaml` and set `theme: one-dark-green`
* Or make an alias `alias hl='hl --theme one-dark-green'`

new: `universal` theme is now default

---

Cargo.lock
Cargo.toml
src/app.rs
src/error.rs
src/fsmon.rs
src/input.rs
src/lib.rs

Now a command like `hl -F *.log` may be used to follow multiple log files by filename (equivalent to `tail -F` command) and reload file automatically if it is deleted and re-created or truncated.

new: Monitor file changes in follow mode

---

etc/defaults/config.yaml

The check is case-sensitive, adding some more normal casing cases.

Add more values to match

---

Cargo.lock
Cargo.toml
README.md
benches/parse-and-format.rs
src/app.rs
src/formatting.rs
src/lib.rs
src/main.rs
src/model.rs
src/serdex.rs

* Added option `--raw` to request output of raw source JSON messages instead of formatted messages.
* Flag `-r` that previously served as a shortcut for `--raw-fields` is now a shortcut for `--raw` option.

new: Added option for raw source message output

---

Cargo.lock
Cargo.toml
etc/defaults/config-ecs.yaml
src/formatting.rs
src/model.rs
src/settings.rs
src/types.rs

* Added support for predefined field names that can match fields in nested objects when used with dot delimiters.
For example, if `log.origin.file.name' is used for a predefined field name, it will match any of the 
* `{ "log.origin.file.name": "app.py" }`
* `{ "log": { "origin.file.name": "app.py" } }`
* `{ "log": { "origin": {"file.name": "app.py" } } }`
* `{ "log": { "origin": {"file": {"name": "app.py" } } } }`
* etc.
* Added predefined `caller-file` and `caller-line` fields for separate processing of file name and line number.
Example output
```
23-11-02 08:09:10.423 |INF| __main__: backup for database bar in foo is already done today application='backup-rds' ecs={ version='1.6.0' } language='python' process={ name='MainProcess' pid=1 thread={ id=140610736142144 name='MainThread' } } …
```

new: Added support for configuration compatible with ECS log format

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/formatting.rs
src/main.rs

* Added option to allow non-JSON prefixes before JSON messages.
* Command-line option: `--allow-prefix`
* Environment variable: `HL_ALLOW_PREFIX`
* Prefix mode is now disabled by default since it proved to produce undesired behavior for some input data.
* Changes behavior introduced in #108
* See original feature request: #105

new: Added option `--allow-prefix`

---

Cargo.lock
Cargo.toml
README.md
benches/parse-and-format.rs
src/app.rs
src/error.rs
src/formatting.rs
src/level.rs
src/lib.rs
src/main.rs
src/model.rs
src/query.pest
src/query.rs

- Command
```
$ hl my-service.log --query 'level > info or status-code >= 400 or duration > 0.5'
```
Displays messages that either have a level higher than info (i.e. warning or error) or have a status code field with a numeric value >= 400 or a duration field with a numeric value >= 0.5.
- Command
```
$ hl my-service.log -q '(request in (95c72499d9ec, 9697f7aa134f, bc3451d0ad60)) or (method != GET)'
```
Displays all messages that have the 'request' field with one of these values, or the 'method' field with a value other than 'GET'.
- Complete set of supported operators
* Logical operators
* Logical conjunction - `and`, `&&`
* Logical disjunction - `or`, `||`
* Logical negation - `not`, `!`
* Comparison operators
* Equal - `eq`, `=`
* Not equal - `ne`, `!=`
* Greater than - `gt`, `>`
* …

new: Added `--query` option

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/input.rs
src/main.rs

Option `--tail` allows to specify number of recent lines that should be preloaded in each file when using `--follow` mode.
Default value is 10.

new: Added `--tail` parameter for `--follow` mode

---

Cargo.lock
Cargo.toml
src/model.rs
src/query.rs

Replaced [wildmatch](https://crates.io/crates/wildmatch) with [wildflower](https://crates.io/crates/wildflower).

new: Improved wildcard matching performance

---

Cargo.lock
Cargo.toml
src/filtering.rs

* `hl -h 'agent-*'` hides all fields with 'agent-' prefix.
* `hl -h '*' -h '!agent-*'` hides all fields except fields with 'agent-' prefix.
* `hl -h 'agent.*' -h '!agent.name'` hides all fields inside 'agent' object except 'name' field.
* Mixed hiding and unhiding with overlapping patterns at the same key path level is not supported and may produce unexpected results. For example, `hl -h 'agent.*' -h '!agent.i*' -h 'agent.?*'`.

new: Added wildcard support to `--hide` option

---

Cargo.lock
Cargo.toml
src/input.rs

Fixed `--tail` preloading if input file contains less lines than requested in `--follow` mode.

fix: Fixed tail preloading if input file contains less lines than requested

---

Cargo.lock
Cargo.toml
src/logfmt/de.rs

There is no standard for the `logfmt` format, there are just a few implementations that are usually used as a reference.
I haven't seen them all, but the [go implementation](https://pkg.go.dev/github.com/kr/logfmt), which is usually referenced as the source, seems to have an overly simplified definition of the format that behaves strangely. It parses almost any [garbage](https://go.dev/play/p/CcL8I-OEM0T) that doesn't look like a logfmt format.
Also, some log aggregators, such as [AppSignal](https://docs.appsignal.com/logging/formatting/logfmt.html), have restrictions on valid characters in the keys.
I would prefer to leave logs that don't look like `logfmt` or `json` unchanged.
So I decided to limit the allowed characters in `logfmt` keys to letters, digits, dashes, dots, underscores, …

new: Stricter logfmt keys parsing

---

Cargo.lock
Cargo.toml
src/logfmt/de.rs

* Only ASCII whitespace and control characters are now allowed between `<key>`=`<value>` pairs.
* Allowed characters in keys of logfmt format have been relaxed after the change in #148. The allowed characters in keys have been expanded to include Unicode characters as well as the following yellow ASCII characters:

new: Changed allowed logfmt formatting

---

Cargo.lock
Cargo.toml
src/timestamp.rs

Added support for timestamps represented as a floating point number of seconds, milliseconds, or microseconds since the Unix epoch.
The units are automatically chosen based on the values. If the value is close enough to Unix epoch, it is assumed to be in seconds.

new: Added support for floating point timestamps

---

Cargo.lock
Cargo.toml
src/timestamp.rs

Additional fix for #153 and #154.
Fixes floating point timestamp parsing in case of negative value and zero fractional part.

fix: Fixed timestamp parsing in case of negative value and zero fractional part

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml
src/formatting.rs
src/settings.rs

Quotation marks were recently silently removed when `logfmt` format support was added in #147.
Now a configuration file option has been added to enable or disable quoting.
By default it is set to `false` (disabled), but you can manually override the former behavior by setting it to `true` (enabled).
```yaml
formatting:
add-quotes: false
```

new: Added option to enable or disable quotes

---

Cargo.lock
Cargo.toml
Makefile
README.md
src/app.rs
src/formatting.rs
src/index.rs
src/main.rs
src/model.rs
src/scanning.rs
src/timestamp.rs

Added `--unix-timestamp-unit` option to allow explicit specification of the unit of Unix timestamps, which can be
* seconds
* milliseconds
* microseconds
* nanoseconds
Automatic detection is used by default.
```
--unix-timestamp-unit <UNIX_TIMESTAMP_UNIT>        Unix timestamp unit, [auto, s, ms, us, ns] [env: HL_UNIX_TIMESTAMP_UNIT=] [default: auto] [possible values: auto, s, ms, us, ns]
```

new: Added unix timestamp unit option

---

Cargo.lock
Cargo.toml
README.md
src/app.rs
src/index.rs
src/main.rs
src/model.rs

Added `--input-format` option.
```
--input-format <INPUT_FORMAT>                      Input format [env: HL_INPUT_FORMAT=] [default: auto] [possible values: auto, json, logfmt]
```
Addresses #36

new: Added --input-format option

---

Cargo.lock
Cargo.toml
src/logfmt/de.rs
src/logfmt/error.rs

Lines with invalid utf-8 encoding are now excluded from parsing.
They are displayed as is in default mode, and are completely ignored in `--sort` mode.

fix: Fixed invalid utf-8 handling in logfmt format

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml

Enabled quotes for strings by default, as was the case before release 1.27.0, to avoid unreadable text when using spaces.
Automatic usage of quotes will be implemented soon.

new: Enabled quotes for strings by default

---

Cargo.lock
Cargo.toml
etc/defaults/themes/neutral.yaml
etc/defaults/themes/universal-blue.yaml
etc/defaults/themes/universal.yaml

Changed level separator style in "universal", "universal-blue" themes to "faint".
Changed boolean value color to "default" in  "neutral" theme.

new: Minor improvements in "universal", "universal-blue" and "neutral" themes

---

Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/main.rs

```
JSON and logfmt log converter to human readable representation
Usage: hl [OPTIONS] [FILE]...
Arguments:
[FILE]...  Files to process
Options:
-s, --sort                             Sort messages chronologically
-F, --follow                           Follow input streams and sort messages chronologically during time frame set by --sync-interval-ms option
--tail <N>                         Number of last messages to preload from each file in --follow mode [default: 10]
--sync-interval-ms <MILLISECONDS>  Synchronization interval for live streaming mode enabled by --follow option [default: 100]
--paging <WHEN>                    Control pager usage (HL_PAGER or PAGER) [env: HL_PAGING=] [default: auto] [possible values: auto, always, never]
-P                                     Handful …
```

new: All options are now logically grouped in the help output

---

Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/main.rs

Now `-c` is a flag as it was before, it can be used in a group of flags combined together, and it overrides `--color`.
Additionally, `-c` can now be overridden by `--color`.

fix: Partially reverted #220 due to unexpected breaking changes

---

.tarpaulin.toml
Cargo.lock
Cargo.toml
README.md
src/main.rs
src/themecfg.rs

To select themes with preview [fzf](https://github.com/junegunn/fzf) tool can be used like this:
```bash
hl --list-themes | fzf --preview-window="top,80%" --preview="head -n 100 example.log | hl -c --theme {}"
```

new: Added support for theme preview with `fzf`

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/publish.yml
Cargo.lock
Cargo.toml
README.md
etc/defaults/config.yaml
src/app.rs
src/cli.rs
src/fmtx.rs
src/formatting.rs
src/main.rs
src/model.rs
src/settings.rs
src/theme.rs

* `--flatten` command line option.
* `HL_FLATTEN` environment variable
* `formatting.flatten` configuration file option.
```
--flatten <WHEN>        Whether to flatten objects [env: HL_FLATTEN=] [default: always] [possible values: never, always]
```
The default value is "always", which means that all nested objects are now flattened by default.
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/pamburus/hl/assets/12778560/4d402d21-7d7e-4bfb-b424-41a2bcf90d9c" width="100%">
<source media="(prefers-color-scheme: light)" srcset="https://github.com/pamburus/hl/assets/12778560/05d35425-3447-49fe-a886-916bf4becb08" width="100%">
</picture>
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/pamburus/hl/assets/12778560/149cacc1-027c-40f …

new: Nested objects flattening feature

---

Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/config.rs
src/error.rs
src/main.rs
src/settings.rs

Additionally, improved error handling on configuration file loading.

new: Added command-line option for config file path

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml
src/app.rs
src/formatting.rs
src/model.rs
src/settings.rs

Also changed the default behavior to show them only if present.
Config file changes:
```yaml
fields:
predefined:
time:
show: auto
level:
show: auto
```
Valid values: `auto`, `always`.

new: Added configuration options to force showing time and level fields

---

Cargo.lock
Cargo.toml
src/formatting.rs
src/theme.rs

* Backticks were selected if string contained only single quotes and no other special characters
* Single quotes were selected if string contained backslashes
* Now double quotes are selected if string contains only single quotes
* Now backticks are selected if string contains backslashes but no backticks

fix: Fixed automatic quotes choice in few cases

---

Cargo.lock
Cargo.toml
src/app.rs
src/scanning.rs

The CR-LF sequence was not parsed correctly.
Additionally, empty lines were incorrectly skipped in the output, fixed that also.

fix: Fixed smart new line delimiter logic

---

Cargo.lock
Cargo.toml
src/app.rs
src/index.rs
src/input.rs

If some lines in the input data were empty, some other lines could be lost in the output.

fix: Fixed sorting when some lines are empty

---

Cargo.lock
Cargo.toml
src/app.rs
src/formatting.rs
src/model.rs

String values that look like "false", "true", "null" or like a number will be now quoted automatically to be distinguished from corresponding non-string values.

new: Automatically quote ambiguous string values

---

Cargo.lock
Cargo.toml
etc/defaults/themes/tc24d-b2.yaml
etc/defaults/themes/tc24l-b2.yaml

Added modified versions of tc24d-blue and tc24l-blue themes without bold and reverse attributes on message and levels.

new: Added new dark and light true-color themes `tc24d-b2` and `tc24l-b2`

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml
src/app.rs
src/config.rs
src/model.rs
src/testing/assets/configs/issue-288.yaml

Now in addition to the original spelling found in the configuration file, level values are automatically registered in lower case, upper case and title case.
Closes #288

new: Automatically add different spellings of level values

---

etc/defaults/config.yaml

Added quotation marks to time-zone option in the default configuration file.

fix: Added quotation marks to time-zone option

---

Cargo.lock

* Updating anstream v0.6.14 -> v0.6.15
* Updating bitflags v2.5.0 -> v2.6.0
* Updating colorchoice v1.0.1 -> v1.0.2
* Updating roff v0.2.1 -> v0.2.2
* Updating syn v2.0.66 -> v2.0.72
* Updating version_check v0.9.4 -> v0.9.5
* Updating windows-targets v0.52.5 -> v0.52.6
* Updating windows_aarch64_gnullvm v0.52.5 -> v0.52.6
* Updating windows_aarch64_msvc v0.52.5 -> v0.52.6
* Updating windows_i686_gnu v0.52.5 -> v0.52.6
* Updating windows_i686_msvc v0.52.5 -> v0.52.6
* Updating windows_x86_64_gnu v0.52.5 -> v0.52.6
* Updating windows_x86_64_gnullvm v0.52.5 -> v0.52.6
* Updating windows_x86_64_msvc v0.52.5 -> v0.52.6
* Updating winnow v0.6.15 -> v0.6.16

build(deps): Updated dependencies

---

README.md

This is very minor change that adds syntax coloring to each `sh` block, and removes the prompt character to aid in copying.

Update `sh` blocks in readme

---

Cargo.lock
Cargo.toml
README.md
src/input.rs
src/main.rs

To decode compressed files/streams automatically, not just based on extension.
A gzip usually has .gz as extension, but not always (I have .s, for example).
This could be configurable, but I think checking the magic two \x1f\x8b starting bytes would be more adequate.
The simplest thing would be reading the first two bytes of the stream, check it and decide whether to GzDecode it or not.
But I don't know Rust, so that's hard - it's easier to use a ready-made crate, like deko (or autocompress).

Use deko::AnyDecoder instead of flate2::GzDecoder

---

Cargo.lock
Cargo.toml
Makefile
README.md
build/ci/coverage.sh
contrib/bin/screenshot.sh
src/app.rs
src/appdirs.rs
src/cli.rs
src/config.rs
src/main.rs
src/settings.rs
src/themecfg.rs

Changed the way how configuration files are processed.
* Configuration files are automatically loaded if found in predefined platform-specific locations.
| OS      | System-Wide Location                     | User Profile Location                                    |
| ------- | ---------------------------------------- |  ------------------------------------------------------- |
| macOS   | /etc/hl/config.{yaml,toml,json}          | ~/.config/hl/config.{yaml,toml,json}                     |
| Linux   | /etc/hl/config.{yaml,toml,json}          | ~/.config/hl/config.{yaml,toml,json}                     |
| Windows | %PROGRAMDATA%\hl\config.{yaml,toml,json} | %USERPROFILE%\AppData\Roaming\hl\config.{yaml,toml,json} |
* The path to the configuration file can be overridden using the …

feat: added support for multiple configuration files

---

README.md

Thanks for this useful program. A small nit pick for the readme: currently `less` links to a random outdated repository from third-party, it would be better linked to the official homepage instead (or if you prefer, https://github.com/gwsw/less is the official repository).

fix(doc): correct link to less pager

---

Cargo.lock
Cargo.toml
crate/heapopt/Cargo.toml
crate/heapopt/src/lib.rs
crate/heapopt/src/vec.rs
src/fmtx.rs
src/formatting.rs
src/model.rs

Deduplicated heap-optimized vectors all over the project.
Moved as `Vec` to a separate crate `heapopt` and reused wherever possible.

refactor: deduplicated heap-optimized vectors

---

.github/workflows/ci.yml
.gitignore
Cargo.lock
Cargo.toml
src/vfs.rs

fix: workaround for fs::canonicalize failures on fifo files on linux

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/vfs.rs

Merges release/0.30.2 into master
Closes #656

fix: workaround for fs::canonicalize failures on fifo files on linux (#657)

---

Cargo.lock
Cargo.toml
src/model.rs
src/settings.rs

Additional fixes related to #694

fix: fixed handling of empty values for predefined fields

---

README.md

Thanks to @chenrui333 [hl](https://github.com/pamburus/hl) is now available in [homebrew-core](https://github.com/Homebrew/homebrew-core) ([#208082](https://github.com/Homebrew/homebrew-core/pull/208082)) and can be installed with the command
```sh
brew install sh
```
This pull request updates the installation instructions in the README.md accordingly.

feat: updated installation instructions for homebrew

---

Cargo.lock
Cargo.toml
etc/defaults/themes/hl-dark.yaml

fix: fixed warning color in `hl-dark` theme

---

Cargo.lock
Cargo.toml
etc/defaults/themes/hl-dark.yaml
etc/defaults/themes/hl-light.yaml
etc/defaults/themes/uni.yaml
schema/json/theme.schema.json
src/formatting.rs
src/testing/assets/themes/test.toml
src/theme.rs
src/themecfg.rs

Closes #944
Adds support for optional `boolean-true` and `boolean-false` elements in themes.
If specified, settings in these elements override corresponding settings in the `boolean` element.
Changes `false` value color in `uni`, `hl-dark` and `hl-light` themes to red.
Changes `true` value color in `hl-dark` and `hl-light` themes to green.

feat: added distinct style configurations for false and true boolean values

---

Cargo.lock
Cargo.toml
etc/defaults/config.yaml
etc/defaults/themes/ayu-dark-24.yaml
etc/defaults/themes/ayu-light-24.yaml
etc/defaults/themes/ayu-mirage-24.yaml
etc/defaults/themes/classic-light.yaml
etc/defaults/themes/classic-plus.yaml
etc/defaults/themes/classic.yaml
etc/defaults/themes/dmt.yaml
etc/defaults/themes/hl-dark.yaml
etc/defaults/themes/hl-light.yaml
etc/defaults/themes/lsd.yaml
etc/defaults/themes/neutral.yaml
etc/defaults/themes/one-dark-24.yaml
etc/defaults/themes/one-light-24.yaml
etc/defaults/themes/tc24d-b2.yaml
etc/defaults/themes/tc24d-blue.yaml
etc/defaults/themes/tc24l-b2.yaml
etc/defaults/themes/tc24l-blue.yaml
etc/defaults/themes/uni.yaml
etc/defaults/themes/universal-blue.yaml
etc/defaults/themes/universal.yaml
schema/json/config.schema.json
schema/json/theme.schema.json
src/app.rs
src/formatting.rs
src/settings.rs
src/testing/assets/themes/test.toml
src/themecfg.rs

This pull request adds the following options to the configuration file:
```yaml
formatting:
message:
format: delimited
punctuation:
message-delimiter: "::"
```
This also changes the default message format to `delimited`, which improves readability when `=` or various quotation marks are used in messages, while avoiding ambiguity in most cases.
If you don't like the new default formatting style, you can opt out and revert to the previous style by setting `formatting.message.format` to `auto-quoted`.
If you don't care about ambiguity and want to avoid quotation marks and escaping, set `formatting.message.format` to `raw`.
Closes #907

feat: added message format setting

---

.gitignore
Cargo.lock
Cargo.toml
src/model.rs
src/query.pest

Adds support for filtering by array items.
Supported variants include
* Matching any item in the array
```
hl -f 'span.[].name=a'
```
* Matching an exact item in the array 
```
hl -f 'span.[0].name=a'
```
Closes #964

feat: added filtering by array items

---

Cargo.lock

| Package | From | To |
| --- | --- | --- |
| [bitflags](https://github.com/bitflags/bitflags) | `2.8.0` | `2.9.4` |
| [getrandom](https://github.com/rust-random/getrandom) | `0.3.2` | `0.3.3` |
| [hashbrown](https://github.com/rust-lang/hashbrown) | `0.15.2` | `0.15.5` |
| [proc-macro-crate](https://github.com/bkchr/proc-macro-crate) | `3.3.0` | `3.4.0` |
Updates `bitflags` from 2.8.0 to 2.9.4
- [Release notes](https://github.com/bitflags/bitflags/releases)
- [Changelog](https://github.com/bitflags/bitflags/blob/main/CHANGELOG.md)
- [Commits](https://github.com/bitflags/bitflags/compare/2.8.0...2.9.4)
Updates `getrandom` from 0.3.2 to 0.3.3
- [Release notes](https://github.com/rust-random/getrandom/releases)
- [Changelog](https://github.com/rust-random/getrandom/blob/master/CHANGELOG.md) …

build(deps): bump all dependencies with 4 updates

---

justfile

This removes accidentally added `-vv` option for `git-cliff` in #1066.

chore(just): added `just changes`

---

Cargo.lock
Cargo.toml
README.md
flake.nix
justfile
nix/binary-hashes.nix
nix/binary-package.nix

This pull request adds a binary package `bin` for Nix which uses pre-built binaries from [releases](https://github.com/pamburus/hl/releases).
The binary package offers:
- **Faster installation** - No compilation required
- **Reduced dependencies** - No need for Rust toolchain
- **Consistent builds** - Uses the same binaries as GitHub releases
Run directly:
```sh
nix run github:pamburus/hl#bin
```
Add to profile:
```sh
nix profile add github:pamburus/hl#bin
```
Add to NixOS system configuration:
```nix
{
inputs = {
nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";
hl.url = "github:pamburus/hl";
};
outputs = {nixpkgs, hl, ...}:
let
system = "x86_64-linux";
in
{
nixosConfigurations.yourHost = nixpkgs.lib.nixosSystem {
inherit system;
modules = [
({...}: {
environment.systemPackages = [ …
```

feat(nix): added binary nix package

---

.github/workflows/release.yml

This pull request fixes typo in GitHub token for the last step introduced in #1073.

build(release): added release workflow

---

Cargo.lock

| Package | From | To |
| --- | --- | --- |
| anstyle | v1.0.11 | v1.0.13 |
| js-sys | v0.3.80 | v0.3.81 |
| pest | v2.8.2 | v2.8.3 |
| pest_derive | v2.8.2 | v2.8.3 |
| pest_generator | v2.8.2 | v2.8.3 |
| pest_meta | v2.8.2 | v2.8.3 |
| thiserror | v2.0.16 | v2.0.17 |
| thiserror-impl | v2.0.16 | v2.0.17 |
| wasm-bindgen | v0.2.103 | v0.2.104 |
| wasm-bindgen-backend | v0.2.103 | v0.2.104 |
| wasm-bindgen-macro | v0.2.103 | v0.2.104 |
| wasm-bindgen-macro-support | v0.2.103 | v0.2.104 |
| wasm-bindgen-shared | v0.2.103 | v0.2.104 |
| web-sys | v0.3.80 | v0.3.81 |
| windows-link | v0.1.3 | ❌ |
| windows-sys | v0.61.0 | v0.61.1 |
| windows-targets | v0.53.3 | v0.53.4 |

build(deps): bump patch updates
